CREATE TABLE users(
    id INT NOT NULL AUTO_INCREMENT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP DEFAULT NULL,
    email VARCHAR(255) NOT NULL UNIQUE ,
    name VARCHAR(255) NOT NULL,
    nim VARCHAR(20) NOT NULL UNIQUE,
    id_prodi INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_id_prodi FOREIGN KEY (id_prodi) REFERENCES program_studies(id)
)ENGINE = InnoDB;