CREATE TABLE subjects(
    id INT NOT NULL AUTO_INCREMENT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP DEFAULT NULL,
    name VARCHAR(100) NOT NULL UNIQUE,
    curriculum VARCHAR(10) NOT NULL,
    sks INT NOT NULL,
    id_prodi INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_id_prod FOREIGN KEY (id_prodi) REFERENCES program_studies(id)
)ENGINE = InnoDB;