ALTER TABLE major_schedules
RENAME TO subject_schedules;

ALTER TABLE subject_schedules
ADD COLUMN createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER id,
ADD COLUMN updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER createdAt,
ADD COLUMN deletedAt TIMESTAMP DEFAULT NULL AFTER updatedAt;